### ISSUE TITLE
Update the header image

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Website#84]
It's still showing as the old login page.

**Comment by jbrooksuk** [comment]
@joecohens you generated the old screenshot in the browser, could you do this again please?

**Comment by joecohens** [comment]
Sure! Also I'm setting the image to the index page instead of the login

**Comment by jbrooksuk** [comment]
:+1:

**Comment by jbrooksuk** [comment]
That makes more sense :P
