### ISSUE TITLE
Blog Link

### ISSUE THREAD

**Issue by GrahamCampbell** [cachethq/Website#88]
Why did you remove the `(1)` thing from the blog link? It was drawing people to click it.

**Comment by jbrooksuk** [comment]
Nope, it only shows a number when there are blog posts within the last week.

**Comment by GrahamCampbell** [comment]
I think we should always show it.

**Comment by GrahamCampbell** [comment]
It draws people to click the link.

**Comment by jbrooksuk** [comment]
I have another idea.
